export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_ADD_COURSE_REQUEST = "USER_ADD_COURSE_REQUEST";
export const USER_ADD_COURSE_SUCCESS = "USER_ADD_COURSE_SUCCESS";
export const USER_ADD_COURSE_FAIL = "USER_ADD_COURSE_FAIL";

export const USER_ADD_CHAPTER_REQUEST = "USER_ADD_CHAPTER_REQUEST";
export const USER_ADD_CHAPTER_SUCCESS = "USER_ADD_CHAPTER_SUCCESS";
export const USER_ADD_CHAPTER_FAIL = "USER_ADD_CHAPTER_FAIL";

export const USER_ADD_SUBTOPIC_REQUEST = "USER_ADD_SUBTOPIC_REQUEST";
export const USER_ADD_SUBTOPIC_SUCCESS = "USER_ADD_SUBTOPIC_SUCCESS";
export const USER_ADD_SUBTOPIC_FAIL = "USER_ADD_SUBTOPIC_FAIL";

export const USER_ADD_COUNTER_REQUEST = "USER_ADD_COUNTER_REQUEST";
export const USER_ADD_COUNTER_SUCCESS = "USER_ADD_COUNTER_SUCCESS";
export const USER_ADD_COUNTER_FAIL = "USER_ADD_COUNTER_FAIL";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_CLEAR_ITEMS = "CART_RESET";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
